network_params:
  lr: 0.001
fixeddqn_params:
  tau: 500
dqn_params:
  memory_size: 10000
  batch_size: 32
  pretrain_length: 2000
  num_episodes: 10000
  steps_per_episode: 100000
  explore_probability: 1.0
  gamma: 0.99
  explore_decay: 0.99
ui_params:
  render: False
task_params:
  target_score: 3000
  consistency: 100
  stack_size: 4
  state_type: 'image'
app_params:
  outputdir: "../weights/"
  weightFile: "spaceinvaders"
train: True 
environment: 'SpaceInvaders-v0'