network_params:
  lr: 0.00025
fixeddqn_params:
  tau: 1 
dqn_params:
  memory_size: 1000000
  batch_size: 32
  pretrain_length: 50000
  num_episodes: 50000
  steps_per_episode: 100000
  explore_probability: 1.0
  gamma: 0.99
  explore_decay: 0.99
ui_params:
  render: False 
task_params:
  target_score: 3000
  consistency: 100
  stack_size: 4
  state_type: 'image'
  update_frequency: 4
app_params:
  outputdir: "../weights/"
  weightFile: "spaceinvaders"
train: True 
environment: 'SpaceInvaders-v0'
